export BLACKPARROT_ROOT=$DV_ROOT/design/chip/tile/blackparrot
export BLACKPARROT_RTL_DIR=$BLACKPARROT_ROOT/black-parrot
export BLACKPARROT_SUBSYSTEMS_DIR=$BLACKPARROT_ROOT/black-parrot-subsystems
export BP_COMMON_DIR=$BLACKPARROT_RTL_DIR/bp_common
export BP_TOP_DIR=$BLACKPARROT_RTL_DIR/bp_top
export BP_FE_DIR=$BLACKPARROT_RTL_DIR/bp_fe
export BP_BE_DIR=$BLACKPARROT_RTL_DIR/bp_be
export BP_ME_DIR=$BLACKPARROT_RTL_DIR/bp_me
export BP_EXTERNAL_DIR=$BLACKPARROT_RTL_DIR/external
export BASEJUMP_STL_DIR=$BP_EXTERNAL_DIR/basejump_stl
export HARDFLOAT_DIR=$BP_EXTERNAL_DIR/HardFloat

