// Modified by Princeton University on June 9th, 2015
/*
* ========== Copyright Header Begin ==========================================
* 
* OpenSPARC T1 Processor File: Configsrch.H
* Copyright (c) 2006 Sun Microsystems, Inc.  All Rights Reserved.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES.
* 
* The above named program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License version 2 as published by the Free Software Foundation.
* 
* The above named program is distributed in the hope that it will be 
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
* 
* You should have received a copy of the GNU General Public
* License along with this work; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
* 
* ========== Copyright Header End ============================================
*/
//----------------------------------------------------------------------
// File                 :  IverFile.H
// Creation Date        :  Wed Jun  7 09:03:05 PDT 1995
// Description          :  Header file for TRE configsrch program files
//----------------------------------------------------------------------

#ifndef _CONFIGSRCH_VARS
#define _CONFIGSRCH_VARS

static const int MAXENVSIZE  = 4096;
static const int MAXNAMESIZE = 1024;
static const int MAXSIZE     = 1024;
static const int MAXFILES    =   32;

static const int FALSE = 0;
static const int TRUE  = 1;
extern char  PROGRAM[MAXSIZE];                    // program name


#endif
