# Bitstream Configuration
# ------------------------------------------------------------------------
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK Enable [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 63.8 [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN disable [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR Yes [current_design]
# ------------------------------------------------------------------------

# Don't time the GPIO reset signals
set_false_path -from [get_pins -hier *Not_Dual.gpio_Data_Out_reg*/C]



# 156.25MHz General purpose system clock
set_property PACKAGE_PIN AU19 [get_ports chipset_clk_osc_p]
set_property PACKAGE_PIN AV19 [get_ports chipset_clk_osc_n]

set_property IOSTANDARD LVDS [get_ports chipset_clk*]


set_property PACKAGE_PIN AL20 [get_ports resetn]
set_property IOSTANDARD LVCMOS12 [get_ports resetn]


# UART
set_property PACKAGE_PIN BF18 [get_ports uart_rx]
set_property PACKAGE_PIN BB20 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS12 [get_ports uart_*]

##
## PCIe MGTY Interface
##
set_property PACKAGE_PIN BD21 [get_ports pcie_perstn]
set_property IOSTANDARD LVCMOS12 [get_ports pcie_perstn]

set_property PACKAGE_PIN BC2 [get_ports {pci_express_x16_rxp[15]}]
set_property PACKAGE_PIN BC1 [get_ports {pci_express_x16_rxn[15]}]
set_property PACKAGE_PIN BF5 [get_ports {pci_express_x16_txp[15]}]
set_property PACKAGE_PIN BF4 [get_ports {pci_express_x16_txn[15]}]
set_property PACKAGE_PIN BA2 [get_ports {pci_express_x16_rxp[14]}]
set_property PACKAGE_PIN BA1 [get_ports {pci_express_x16_rxn[14]}]
set_property PACKAGE_PIN BD5 [get_ports {pci_express_x16_txp[14]}]
set_property PACKAGE_PIN BD4 [get_ports {pci_express_x16_txn[14]}]
set_property PACKAGE_PIN AW4 [get_ports {pci_express_x16_rxp[13]}]
set_property PACKAGE_PIN AW3 [get_ports {pci_express_x16_rxn[13]}]
set_property PACKAGE_PIN BB5 [get_ports {pci_express_x16_txp[13]}]
set_property PACKAGE_PIN BB4 [get_ports {pci_express_x16_txn[13]}]
set_property PACKAGE_PIN AV2 [get_ports {pci_express_x16_rxp[12]}]
set_property PACKAGE_PIN AV1 [get_ports {pci_express_x16_rxn[12]}]
set_property PACKAGE_PIN AV7 [get_ports {pci_express_x16_txp[12]}]
set_property PACKAGE_PIN AV6 [get_ports {pci_express_x16_txn[12]}]
# Clock
set_property PACKAGE_PIN AM10 [get_ports pcie_refclk_clk_n]
set_property PACKAGE_PIN AM11 [get_ports pcie_refclk_clk_p]

set_property PACKAGE_PIN AU4 [get_ports {pci_express_x16_rxp[11]}]
set_property PACKAGE_PIN AU3 [get_ports {pci_express_x16_rxn[11]}]
set_property PACKAGE_PIN AU9 [get_ports {pci_express_x16_txp[11]}]
set_property PACKAGE_PIN AU8 [get_ports {pci_express_x16_txn[11]}]
set_property PACKAGE_PIN AT2 [get_ports {pci_express_x16_rxp[10]}]
set_property PACKAGE_PIN AT1 [get_ports {pci_express_x16_rxn[10]}]
set_property PACKAGE_PIN AT7 [get_ports {pci_express_x16_txp[10]}]
set_property PACKAGE_PIN AT6 [get_ports {pci_express_x16_txn[10]}]
set_property PACKAGE_PIN AP2 [get_ports {pci_express_x16_rxp[8]}]
set_property PACKAGE_PIN AP1 [get_ports {pci_express_x16_rxn[8]}]
set_property PACKAGE_PIN AP7 [get_ports {pci_express_x16_txp[8]}]
set_property PACKAGE_PIN AP6 [get_ports {pci_express_x16_txn[8]}]
set_property PACKAGE_PIN AR4 [get_ports {pci_express_x16_rxp[9]}]
set_property PACKAGE_PIN AR3 [get_ports {pci_express_x16_rxn[9]}]
set_property PACKAGE_PIN AR9 [get_ports {pci_express_x16_txp[9]}]
set_property PACKAGE_PIN AR8 [get_ports {pci_express_x16_txn[9]}]
set_property PACKAGE_PIN AN4 [get_ports {pci_express_x16_rxp[7]}]
set_property PACKAGE_PIN AN3 [get_ports {pci_express_x16_rxn[7]}]
set_property PACKAGE_PIN AN9 [get_ports {pci_express_x16_txp[7]}]
set_property PACKAGE_PIN AN8 [get_ports {pci_express_x16_txn[7]}]
set_property PACKAGE_PIN AM2 [get_ports {pci_express_x16_rxp[6]}]
set_property PACKAGE_PIN AM1 [get_ports {pci_express_x16_rxn[6]}]
set_property PACKAGE_PIN AM7 [get_ports {pci_express_x16_txp[6]}]
set_property PACKAGE_PIN AM6 [get_ports {pci_express_x16_txn[6]}]
set_property PACKAGE_PIN AL4 [get_ports {pci_express_x16_rxp[5]}]
set_property PACKAGE_PIN AL3 [get_ports {pci_express_x16_rxn[5]}]
set_property PACKAGE_PIN AL9 [get_ports {pci_express_x16_txp[5]}]
set_property PACKAGE_PIN AL8 [get_ports {pci_express_x16_txn[5]}]
set_property PACKAGE_PIN AK2 [get_ports {pci_express_x16_rxp[4]}]
set_property PACKAGE_PIN AK1 [get_ports {pci_express_x16_rxn[4]}]
set_property PACKAGE_PIN AK7 [get_ports {pci_express_x16_txp[4]}]
set_property PACKAGE_PIN AK6 [get_ports {pci_express_x16_txn[4]}]
#set_property PACKAGE_PIN AL14             [get_ports {pcie_clk0_n} ]                       ;# Bank 227 - MGTREFCLK0N_227
#set_property PACKAGE_PIN AL15             [get_ports {pcie_clk0_n} ]                       ;# Bank 227 - MGTREFCLK0P_227
#set_property PACKAGE_PIN AK12             [get_ports {sys_clk2_n} ]                        ;# Bank 227 - MGTREFCLK1N_227
#set_property PACKAGE_PIN AK13             [get_ports {sys_clk2_n} ]                        ;# Bank 227 - MGTREFCLK1P_227
set_property PACKAGE_PIN AJ4 [get_ports {pci_express_x16_rxp[3]}]
set_property PACKAGE_PIN AJ3 [get_ports {pci_express_x16_rxn[3]}]
set_property PACKAGE_PIN AJ9 [get_ports {pci_express_x16_txp[3]}]
set_property PACKAGE_PIN AJ8 [get_ports {pci_express_x16_txn[3]}]
set_property PACKAGE_PIN AH2 [get_ports {pci_express_x16_rxp[2]}]
set_property PACKAGE_PIN AH1 [get_ports {pci_express_x16_rxn[2]}]
set_property PACKAGE_PIN AH7 [get_ports {pci_express_x16_txp[2]}]
set_property PACKAGE_PIN AH6 [get_ports {pci_express_x16_txn[2]}]
set_property PACKAGE_PIN AG4 [get_ports {pci_express_x16_rxp[1]}]
set_property PACKAGE_PIN AG3 [get_ports {pci_express_x16_rxn[1]}]
set_property PACKAGE_PIN AG9 [get_ports {pci_express_x16_txp[1]}]
set_property PACKAGE_PIN AG8 [get_ports {pci_express_x16_txn[1]}]
set_property PACKAGE_PIN AF2 [get_ports {pci_express_x16_rxp[0]}]
set_property PACKAGE_PIN AF1 [get_ports {pci_express_x16_rxn[0]}]
set_property PACKAGE_PIN AF7 [get_ports {pci_express_x16_txp[0]}]
set_property PACKAGE_PIN AF6 [get_ports {pci_express_x16_txn[0]}]

create_clock -period 10.000 -name pcie_refclk [get_ports pcie_refclk_clk_p]
set_clock_groups -asynchronous -group pcie_refclk

#There are other 3 DDR chips in the u200, here it is only the C0
#300MHz DDR0 system clock
set_property PACKAGE_PIN AY37 [get_ports mc_clk_p]
set_property PACKAGE_PIN AY38 [get_ports mc_clk_n]

set_property -dict {PACKAGE_PIN AR36 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[16]}]
set_property -dict {PACKAGE_PIN AP36 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[15]}]
#set_property -dict {PACKAGE_PIN AN34 IOSTANDARD SSTL12_DCI     } [get_ports ddr4_sdram_c0_odt[1]   ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_ODT1"    - IO_L22N_T3U_N7_DBC_AD0N_42
#set_property -dict {PACKAGE_PIN AM34 IOSTANDARD SSTL12_DCI     } [get_ports ddr4_sdram_c0_cs_n[3]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CS_B3"   - IO_L22P_T3U_N6_DBC_AD0P_42
set_property -dict {PACKAGE_PIN AR33 IOSTANDARD SSTL12_DCI} [get_ports {ddr_cs_n[0]}]
set_property -dict {PACKAGE_PIN AN36 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[13]}]
#set_property -dict {PACKAGE_PIN AN35 IOSTANDARD SSTL12_DCI     } [get_ports ddr_addr[17]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_ADR17"   - IO_L24P_T3U_N10_42
set_property -dict {PACKAGE_PIN AP35 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[14]}]
set_property -dict {PACKAGE_PIN AP34 IOSTANDARD SSTL12_DCI} [get_ports {ddr_odt[0]}]
#set_property -dict {PACKAGE_PIN AP33 IOSTANDARD SSTL12_DCI     } [get_ports ddr4_sdram_c0_cs_n[1]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CS_B1"   - IO_L20N_T3L_N3_AD1N_42
#set_property -dict {PACKAGE_PIN AN33 IOSTANDARD SSTL12_DCI     } [get_ports ddr4_sdram_c0_cs_n[2]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CS_B2"   - IO_L20P_T3L_N2_AD1P_42
set_property -dict {PACKAGE_PIN AT35 IOSTANDARD SSTL12_DCI} [get_ports {ddr_ba[0]}]
set_property -dict {PACKAGE_PIN AR35 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[10]}]
set_property -dict {PACKAGE_PIN AW38 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr_ck_n[0]}]
set_property -dict {PACKAGE_PIN AV38 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr_ck_p[0]}]
#set_property -dict {PACKAGE_PIN AU35 IOSTANDARD DIFF_SSTL12_DCI} [get_ports ddr_ck_n[1]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CK_C1"   - IO_L16N_T2U_N7_QBC_AD3N_42
#set_property -dict {PACKAGE_PIN AU34 IOSTANDARD DIFF_SSTL12_DCI} [get_ports ddr_ck_p[1]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CK_T1"   - IO_L16P_T2U_N6_QBC_AD3P_42
set_property -dict {PACKAGE_PIN AT34 IOSTANDARD SSTL12_DCI} [get_ports {ddr_ba[1]}]
set_property -dict {PACKAGE_PIN AU36 IOSTANDARD SSTL12_DCI} [get_ports ddr_parity]
set_property -dict {PACKAGE_PIN AT36 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[0]}]
set_property -dict {PACKAGE_PIN AV37 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[2]}]
set_property -dict {PACKAGE_PIN AV36 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[1]}]
set_property -dict {PACKAGE_PIN AW36 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[4]}]
set_property -dict {PACKAGE_PIN AW35 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[3]}]
#set_property -dict {PACKAGE_PIN BA38 IOSTANDARD LVCMOS12       } [get_ports ddr4_sdram_c0_alert_n  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_ALERT_B" - IO_L11N_T1U_N9_GC_42
set_property -dict {PACKAGE_PIN BA37 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[8]}]
set_property -dict {PACKAGE_PIN BA40 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[7]}]
set_property -dict {PACKAGE_PIN BA39 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[11]}]
set_property -dict {PACKAGE_PIN BB37 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[9]}]
set_property -dict {PACKAGE_PIN AY36 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[5]}]
set_property -dict {PACKAGE_PIN AY35 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[6]}]
#set_property -dict {PACKAGE_PIN BC40 IOSTANDARD SSTL12_DCI     } [get_ports ddr_cke[1]   ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CKE1"    - IO_L9N_T1L_N5_AD12N_42
set_property -dict {PACKAGE_PIN BC39 IOSTANDARD SSTL12_DCI} [get_ports {ddr_bg[1]}]
set_property -dict {PACKAGE_PIN BB40 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[12]}]
set_property -dict {PACKAGE_PIN BB39 IOSTANDARD SSTL12_DCI} [get_ports ddr_act_n]
set_property -dict {PACKAGE_PIN BC38 IOSTANDARD SSTL12_DCI} [get_ports {ddr_cke[0]}]
set_property -dict {PACKAGE_PIN BC37 IOSTANDARD SSTL12_DCI} [get_ports {ddr_bg[0]}]
set_property -dict {PACKAGE_PIN BF43 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[66]}]
set_property -dict {PACKAGE_PIN BF42 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[67]}]
set_property -dict {PACKAGE_PIN BF38 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[16]}]
set_property -dict {PACKAGE_PIN BE38 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[16]}]
set_property -dict {PACKAGE_PIN BD40 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[64]}]
set_property -dict {PACKAGE_PIN BD39 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[65]}]
set_property -dict {PACKAGE_PIN BF41 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[71]}]
set_property -dict {PACKAGE_PIN BE40 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[70]}]
set_property -dict {PACKAGE_PIN BF37 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[68]}]
set_property -dict {PACKAGE_PIN BE37 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[69]}]
set_property -dict {PACKAGE_PIN BF40 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[17]}]
set_property -dict {PACKAGE_PIN BF39 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[17]}]
set_property -dict {PACKAGE_PIN AU32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[34]}]
set_property -dict {PACKAGE_PIN AT32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[35]}]
set_property -dict {PACKAGE_PIN AM32 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[8]}]
set_property -dict {PACKAGE_PIN AM31 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[8]}]
#set_property -dict {PACKAGE_PIN AT33 IOSTANDARD LVCMOS12       } [get_ports ddr4_sdram_c0_event_n  ]; # Bank 41 VCCO - VCC1V2 Net "DDR4_C0_EVENT_B" - IO_T3U_N12_41
set_property -dict {PACKAGE_PIN AM30 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[33]}]
set_property -dict {PACKAGE_PIN AL30 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[32]}]
set_property -dict {PACKAGE_PIN AR32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[38]}]
set_property -dict {PACKAGE_PIN AR31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[39]}]
set_property -dict {PACKAGE_PIN AN32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[37]}]
set_property -dict {PACKAGE_PIN AN31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[36]}]
set_property -dict {PACKAGE_PIN AP31 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[9]}]
set_property -dict {PACKAGE_PIN AP30 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[9]}]
set_property -dict {PACKAGE_PIN AV32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[25]}]
set_property -dict {PACKAGE_PIN AV31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[24]}]
set_property -dict {PACKAGE_PIN AW33 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[6]}]
set_property -dict {PACKAGE_PIN AV33 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[6]}]
set_property -dict {PACKAGE_PIN AU31 IOSTANDARD LVCMOS12} [get_ports ddr_reset_n]
set_property -dict {PACKAGE_PIN AW34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[27]}]
set_property -dict {PACKAGE_PIN AV34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[26]}]
set_property -dict {PACKAGE_PIN AY31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[29]}]
set_property -dict {PACKAGE_PIN AW31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[28]}]
set_property -dict {PACKAGE_PIN BA35 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[30]}]
set_property -dict {PACKAGE_PIN BA34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[31]}]
set_property -dict {PACKAGE_PIN BA33 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[7]}]
set_property -dict {PACKAGE_PIN BA32 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[7]}]
set_property -dict {PACKAGE_PIN BB32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[17]}]
set_property -dict {PACKAGE_PIN BB31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[16]}]
set_property -dict {PACKAGE_PIN BB36 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[4]}]
set_property -dict {PACKAGE_PIN BB35 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[4]}]
set_property -dict {PACKAGE_PIN AY33 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[19]}]
set_property -dict {PACKAGE_PIN AY32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[18]}]
set_property -dict {PACKAGE_PIN BC33 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[21]}]
set_property -dict {PACKAGE_PIN BC32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[20]}]
set_property -dict {PACKAGE_PIN BC34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[23]}]
set_property -dict {PACKAGE_PIN BB34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[22]}]
set_property -dict {PACKAGE_PIN BD31 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[5]}]
set_property -dict {PACKAGE_PIN BC31 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[5]}]
set_property -dict {PACKAGE_PIN BE33 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[58]}]
set_property -dict {PACKAGE_PIN BD33 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[57]}]
set_property -dict {PACKAGE_PIN BE36 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[14]}]
set_property -dict {PACKAGE_PIN BE35 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[14]}]
set_property -dict {PACKAGE_PIN BD35 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[59]}]
set_property -dict {PACKAGE_PIN BD34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[56]}]
set_property -dict {PACKAGE_PIN BF33 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[61]}]
set_property -dict {PACKAGE_PIN BF32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[60]}]
set_property -dict {PACKAGE_PIN BF35 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[63]}]
set_property -dict {PACKAGE_PIN BF34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[62]}]
set_property -dict {PACKAGE_PIN BE32 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[15]}]
set_property -dict {PACKAGE_PIN BE31 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[15]}]
set_property -dict {PACKAGE_PIN AP29 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[40]}]
set_property -dict {PACKAGE_PIN AP28 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[41]}]
set_property -dict {PACKAGE_PIN AL29 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[10]}]
set_property -dict {PACKAGE_PIN AL28 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[10]}]
set_property -dict {PACKAGE_PIN AN27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[42]}]
set_property -dict {PACKAGE_PIN AM27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[43]}]
set_property -dict {PACKAGE_PIN AR28 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[47]}]
set_property -dict {PACKAGE_PIN AR27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[46]}]
set_property -dict {PACKAGE_PIN AN29 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[44]}]
set_property -dict {PACKAGE_PIN AM29 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[45]}]
set_property -dict {PACKAGE_PIN AT30 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[11]}]
set_property -dict {PACKAGE_PIN AR30 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[11]}]
set_property -dict {PACKAGE_PIN AV27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[49]}]
set_property -dict {PACKAGE_PIN AU27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[50]}]
set_property -dict {PACKAGE_PIN AU30 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[12]}]
set_property -dict {PACKAGE_PIN AU29 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[12]}]
set_property -dict {PACKAGE_PIN AT28 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[48]}]
set_property -dict {PACKAGE_PIN AT27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[51]}]
set_property -dict {PACKAGE_PIN AV29 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[52]}]
set_property -dict {PACKAGE_PIN AV28 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[55]}]
set_property -dict {PACKAGE_PIN AY30 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[53]}]
set_property -dict {PACKAGE_PIN AW30 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[54]}]
set_property -dict {PACKAGE_PIN AY28 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[13]}]
set_property -dict {PACKAGE_PIN AY27 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[13]}]
set_property -dict {PACKAGE_PIN BA28 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[2]}]
set_property -dict {PACKAGE_PIN BA27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[3]}]
set_property -dict {PACKAGE_PIN BB30 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[0]}]
set_property -dict {PACKAGE_PIN BA30 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[0]}]
set_property -dict {PACKAGE_PIN AW29 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[1]}]
set_property -dict {PACKAGE_PIN AW28 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[0]}]
set_property -dict {PACKAGE_PIN BC27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[6]}]
set_property -dict {PACKAGE_PIN BB27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[7]}]
set_property -dict {PACKAGE_PIN BB29 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[4]}]
set_property -dict {PACKAGE_PIN BA29 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[5]}]
set_property -dict {PACKAGE_PIN BC26 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[1]}]
set_property -dict {PACKAGE_PIN BB26 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[1]}]
set_property -dict {PACKAGE_PIN BF28 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[9]}]
set_property -dict {PACKAGE_PIN BE28 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[8]}]
set_property -dict {PACKAGE_PIN BD29 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[2]}]
set_property -dict {PACKAGE_PIN BD28 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[2]}]
set_property -dict {PACKAGE_PIN BE30 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[10]}]
set_property -dict {PACKAGE_PIN BD30 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[11]}]
set_property -dict {PACKAGE_PIN BF27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[12]}]
set_property -dict {PACKAGE_PIN BE27 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[13]}]
set_property -dict {PACKAGE_PIN BF30 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[14]}]
set_property -dict {PACKAGE_PIN BF29 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[15]}]
set_property -dict {PACKAGE_PIN BE26 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[3]}]
set_property -dict {PACKAGE_PIN BD26 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[3]}]
#

set_property PACKAGE_PIN BC21 [get_ports hbm_cattrip]
set_property IOSTANDARD LVCMOS12 [get_ports hbm_cattrip]
set_property PULLDOWN true [get_ports hbm_cattrip]

set_false_path -from [get_pins chipset/chipset_impl/u200_shell_i/meep_shell_i/ddr4_0/inst/u_ddr4_mem_intfc/u_ddr_cal_top/*/C] -to [get_pins chipset/chipset_impl/init_calib_complete_f_reg/D]
