#!/bin/bash
# Copyright (c) 2016 Princeton University
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Princeton University nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY PRINCETON UNIVERSITY "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL PRINCETON UNIVERSITY BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# DRC Runset and optional golden GDS file
OPENPITON_CALIBRE_DRC_DECK="CALIBRE_DRC_DECK_HERE (.drc.cal)"
OPENPITON_CALIBRE_GOLDEN_GDS_FILE="" ; # Optional, (.gds)

# LVS Runset
OPENPITON_CALIBRE_LVS_DECK="CALIBRE_LVS_DECK_HERE (.lvs.cal)"

# GDS2SP (for doing LVS) and LVS black box cells
# These can be due to internal LVS problems on IP macros,
# std cells that don't get outputted from ICC, etc.
# These should be space separated list of standard cells
# you want black boxed
OPENPITON_GDS2SP_BBOX_CELLS=""
OPENPITON_LVS_BBOX_CELLS=""

# Put any environment variables needed by DRC and LVS here
# Examples (should be specified by DRC/LVS deck):
# export TECHDIR=
# export LAYOUT_SYSTEM=GDSII

if [ -z ${OPENPITON_DRC_RUN+x} ]; then
    # Put any DRC specific environment variables here
    :
fi

if [ -z ${OPENPITON_LVS_RUN+x} ]; then
    # Put any LVS specific environment variables here
    :
fi
