# Derived from piton/tools/pli/iop/Makefile

include ${DV_ROOT}/tools/env/Makefile.system

CPPFLAGS = 
CFLAGS += -I../iop -I../ -fpermissive -fpic $(ICARUS_CC_OPTS)

LIB = libsimpledram_icarus.a
CSRCS = simpledram.cc simpledram.c
LIB_OBJS = simpledram.o

all: $(LIB)
	rm -rf *.o

$(LIB_OBJS):
	$(CCC) $(CPPFLAGS) -c  $(CFLAGS) $(CSRCS)

$(LIB): $(LIB_OBJS)
	ar rv $(LIB) $(LIB_OBJS)

clean:
	rm -rf *.o ${LIB}
